spring
  application:
    name: qmkx-server-config
  cloud:
    config:
      server:
        git:
          uri: http://localhost/qmkx/qmkx-config-repo/
          username
server:
  port: 1201

  spring.cloud.config.server.git.username：访问Git仓库的用户名
  spring.cloud.config.server.git.password：访问Git仓库的用户密码
