server:
  port: 8082


#SpringBootAdmin客户端配置
info
  groupId=@project.groupId@
    artifactId=@project.artifactId@
    version=@project.version@
spring
  boot
    admin
      client.name=UserService
      url=http://localhost:8080

# 配置中心相关配置
spring:
  application:
    name: qmkx-service-sys
  cloud:
    config:
      uri: http://localhost:1201/
      profile: default
      label: master

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/depot
    username: qmkx
    password: 123456

# MyBatis配置
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.zzgele.qmkx.user.pojo


#pagehelper分页插件配置
pagehelper:
  dialect: mysql
  support-methods-arguments: true

